django_app/ad/urls.py
from django.urls import path
from ad.views import AdListView, AdDetailView


urlpatterns = [
    path('', AdListView.as_view(), name='list'),
    path('detail/<pk>/', AdDetailView.as_view(), name='detail'),
]

django_app/conf/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('ad.urls', 'ad'), namespace='ads')),
    path('admin/', admin.site.urls),

]

django_app/ad/models.py
from django.db import models
from cities_light.models import City
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User


class Ad(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def views_up(self):
        self.views += 1
        self.save()

    def viewed_handler(self, session):
        viewed_ads = session.get('ads', {})
        if viewed_ads.get(self.id) is None:
            viewed_ads[self.id] = self.id
            session['ads'] = viewed_ads
            self.views_up()

    class Meta:
        ordering = ('created',)

django_app/ad/views.py
from django.views.generic import ListView, DetailView
from ad.models import Ad


class AdListView(ListView):
    model = Ad
    paginate_by = 12


class AdDetailView(DetailView):
    model = Ad

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ad'].viewed_handler(self.request.session)
        return context

django_app/ad/templates/ad/ad_detail.html
{% extends 'base.html' %}
{% block title %}
    AD | {{ ad.title }}
{% endblock %}

{% block content %}

    <div class="row">
        <div class="header col-md-12">
            <h3 class="text-dark" style="text-align: center">{{ ad.title }}</h3>
        </div>
        <div class="col-md-12" style="margin-bottom: 20px">
            {{ ad.description|safe }}
        </div>

        <div class="col-md-3">
            <p><strong>User: </strong>{{ ad.user.get_full_name }}</p>
        </div>
        <div class="col-md-3">
            <p><strong>Date: </strong>{{ ad.created }}</p>
        </div>
        <div class="col-md-6"></div>

        <div class="col-md-3">
            <p><strong>City: </strong>{{ ad.city.display_name }}</p>
        </div>
        <div class="col-md-3">
            <p><strong>Views: </strong>{{ ad.views }}</p>
        </div>

        <div class="col-md-12">
            <a href="{% url 'ads:list' %}">Back</a>
        </div>
    </div>

{% endblock %}

django_app/ad/templates/ad/ad_list.html
{% extends 'base.html' %}


{% block title %}
    Advertisements
{% endblock %}


{% block content %}
    <h4 style="text-align: center; margin: 20px 20px">Ad list</h4>
    <div class="row">
        {% for ad in ad_list %}
            <div class="col-lg-4 col-md-6" style="margin-bottom: 20px">
                <div class="card  bg-light">
                    <div class=" bg-light">
                        <a href="{% url 'ads:detail' ad.id %}">
                            <h6 class="text-center card-state">{{ ad.title }}</h6>
                        </a>
                    </div>


                    <div class="card-body">
                        <p class="card-text ">
                            {{ ad.description|truncatewords:40 }}
                        </p>
                        <div class="row ">
                            <p class="col-md-6 text-left">{{ ad.user.get_full_name }}</p>
                            <p class="col-md-6 text-right">{{ ad.city.name }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <h5 class="col-md-12">Empty</h5>
        {% endfor %}
    </div>

    {% include 'includes/pagination.html' %}
{% endblock %}

django_app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
</head>
<body>


<div class="container content">
    {% block content %}
    {% endblock %}
</div>

<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>
</body>
</html>

django_app/templates/includes/pagination.html
{% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col-12">
            <div style="margin: 0 auto; width: 260px">
                {% if page_obj.has_previous %}
                    <a class="badge badge-secondary" href="?page=1">&laquo; first</a>
                    <a class="badge badge-default" href="?page={{ page_obj.previous_page_number }}">prev</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="badge badge-info" href="?page={{ page_obj.next_page_number }}">next</a>
                    <a class="badge badge-info" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}